equipment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class ChangeModelModification(models.Model):
    """
    This class represents a modification from a specific parameter value
    to a new one.
    Statuses:
      - neutral: both new and old value are equal
      - valid: new value is compatible with old value (regarding new values
      list)
      - conflict: old value is not compatible with new values list
      - new: no old value. Just a new value
      - missing: no new value
    """
    NEUTRAL = 0
    UNKNOWN = 1
    NEW = 2
    VALID = 3
    CONFLICT = 4
    MISSING = 5

    STATE_CHOICES = (
        (NEUTRAL, 'neutral'),
        (UNKNOWN, 'unknown'),
        (NEW, 'new'),
        (VALID, 'valid'),
        (CONFLICT, 'conflict'),
        (MISSING, 'missing'),
    )

    channel = models.ForeignKey('gissmo.Channel')
    name = models.CharField(max_length=255)
    old_value = models.ForeignKey(
        'gissmo.ParameterValue',
        null=True,
        blank=True,
        related_name='old_modif')
    new_value = models.ForeignKey(
        'gissmo.ParameterValue',
        null=True,
        blank=True,
        related_name='new_modif')
    state = models.IntegerField(
        choices=STATE_CHOICES,
        default=UNKNOWN)

    def get_state(self):
        if not self.new_value:
            return self.MISSING
        if not self.old_value:
            return self.NEW
        both_same = self.old_value.value == self.new_value.value
        values = self.new_value.parameter.parametervalue_set.all()
        compared_values = []
        for value in values:
            compared_values.append(value.value)
        compatible = self.old_value.value in compared_values
        if both_same:
            return self.NEUTRAL
        elif not both_same and compatible:
            return self.VALID
        elif not both_same and not compatible:
            return self.CONFLICT
        # default behaviour
        return self.UNKNOWN

    def _get_values(self):
        "Return all possible values linked to new_value parameter."
        if self.new_value:
            return self.new_value.parameter.parametervalue_set.all()
        return []

    _get_values.short_description = 'Values'

    values = property(_get_values)

    def __str__(self):
        return "%s" % self.name or ''

equipment/templates/changemodel_step1.html
{% extends "admin/base_site.html" %}
{% load admin_static %}
{% load static from staticfiles %}

{% block content %}
{% if form.subject.errors %}
<ol>
  {% for error in form.subject.errors %}
  <li><strong>{{ error|escape }}</strong></li>
  {% endfor %}
</ol>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  {{ form }}<br />
  <input type="submit" value="Submit" />
</form>
{% endblock %}

equipment/templates/changemodel_step2.html
{% extends "admin/base_site.html" %}
{% load admin_static %}

{% block content %}
<style>
tr.neutral  { color: black; }
tr.valid    { color: darkgreen; }
tr.conflict { color: red; }
tr.new      { color: blue; }
tr.missing  { color: lightcoral; }
td.center { text-align: center; }
</style>
<h3>Impacted channel</h3>
<p>Here you can see the difference between old equipment model parameters and new ones.</p>
{% if elements %}
    <ul>
    {% for channel in elements %}
    <li><a href="{% url 'admin:gissmo_chain_change' channel.2 %}?channel={{ channel.1 }}">{{ channel.0 }}</a>
        <table>
          <tr>
            <th>Parameter</th>
            <th>Current</th>
            <th>New</th>
            <th>State</th>
            <th>Available new values</th>
          </tr>
          {% for modification in channel.3 %}
          <tr class="{{ modification.get_state_display }}">
            <td>{{ modification.name }}</td>
            <td>{{ modification.old_value|default:"" }}</td>
            <td>{{ modification.new_value|default:"" }}</td>
            <td class="center">{{ modification.get_state_display }}</td>
            <td>
              {% for value in modification.values %}
                {{ value.value }}<br />
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </li>
    {% endfor %}
    </ul>
{% else %}
<p>{{ message }}</p>
{% endif %}
<p style="color: red;">Don't forget to CHANGE MODEL after changes on each channel!</p>

<h3>Legend</h3>
<table>
  <tr>
    <th>State</th>
    <th>Signification</th>
  </tr>
  <tr class="neutral">
    <td>neutral</td>
    <td>We keep the old value. New default one is equal.</td>
  </tr>
  <tr class="valid">
    <td>valid</td>
    <td>We keep the old value. This one is available in available new values.</td>
  </tr>
  <tr class="conflict">
    <td>conflict</td>
    <td>New value needed as the old one is not available in new values!</td>
  </tr>
  <tr class="new">
    <td>new</td>
    <td>We will create a new parameter with a new default value. Execpt if you exclude it.</td>
  </tr>
  <tr class="missing">
    <td>missing</td>
    <td>We will discard this parameter. Except you include it.</td>
  </tr>
</table>

{% endblock %}